### ISSUE TITLE
Improvements for showing Fragments

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross-AndroidSupport#43] opened 2015-07-08 11:42 UTC
@martijn00 wrote this here #41:

> The main problem with this change is that you use a new activity to show login. Currently the CachingFragment implementation is limited that you first need to show some ViewModel that is connected to the Hosting Activity to show other fragments.
> 
> To work around that it is possible to just use 1 Activity and for everything else use Fragments. The real solution would be to change the code of the FragmentsPresenter to allow to navigate to the correct ViewModel directly.
> 
> Let's say you start the app, depending on if you are already logged in you want to show the LoginViewModel, or the NewsViewModel(let's imagine a news app). It doesn't make sense then that you need to show MainViewModel first in order to show the NewsViewmodel.
> 
> My guess would be we need to turn the registering of fragments around. When we call ShowViewModel we should search for if it is a fragment, and if it is so, we should search for it's parent. I was thinking that could be done by adding an attribute to fragments containing it's parent.

**Comment by Cheesebaron** [comment] 2015-07-08 11:47
The pull created in #41 works fine, showing an Activity before the one with Fragments works fine.

You should also be able to navigate away as the ViewModel type is checked whether it is registered for a specific Fragment Host.

> To work around that it is possible to just use 1 Activity and for everything else use Fragments. The real solution would be to change the code of the FragmentsPresenter to allow to navigate to the correct ViewModel directly.

If we want to do this, it needs to support that multiple ViewModels can be default, because a Fragment is not always full screen.

**Comment by vvolkgang** [comment] 2015-09-22 20:58
@Cheesebaron @martijn00 any updates on this?

**Comment by martijn00** [comment] 2015-09-22 21:21
No not yet.

**Comment by vvolkgang** [comment] 2015-09-22 23:51
Usage idea: Set the parent Activity + ContentId target as an attribute. Presenter would know how to deal with that, enabling the Core to navigate directly.

Given a Drawer + List & Detail + Phone & Tablet scenario, your `AppStart.cs` would be as simple and direct as:

``` csharp
public void Start(object hint = null)
{
    ShowViewModel<MenuViewModel>();
    ShowViewModel<ListViewModel>();
    if (Tablet)
        ShowViewModel<DetailViewModel>();
}
```

This would also enable fragment auto-register in each parent host, take into account #77 and bam, configurate everything in a simple attribute as you already do for Activities (following @kjeremy comment on [#MvvmCross-1138](https://github.com/MvvmCross/MvvmCross/issues/1138#issuecomment-142323927) ).

Any ideas on how to implement such system? Need to see some of the current boilerplate code to know where to start.

**Comment by martijn00** [comment] 2015-09-23 10:29
I think this is a good idea. It could fix the original problem which was described in the OP, and could cleanup some of the current code. Could you make a PR for this?

**Comment by vvolkgang** [comment] 2015-09-23 10:29
This is actually quite simple. Following this [MvxFragmentsPresenter](https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Cirrious.MvvmCross.Droid.Support.Fragging/Presenter/MvxFragmentsPresenter.cs#L74), we just have to:
1. Add the attribute check and if it's present
2. Inflate the Activity
3. Add it in the hosts dictionary
4. Register the Fragment in the host 
5. Use the host to present the fragment

Will create a PR asap. @martijn00 what code do you think we can cleanup afterwards?

**Comment by martijn00** [comment] 2015-09-23 10:37
I would add a general `MvxFragment` attribute, where you can add those things as parameters. Then i would also move the `MvxOwnedViewModelFragment` into that attribute as parameter. That would make https://github.com/MvvmCross/MvvmCross/issues/1138 work out too.

After that you could remove the `RegisterForDetailsRequests` in the MainActivity of the sample. Maybe also make the `RegisterFragment` in the MvxCachingFragmentActivity private.

**Comment by vvolkgang** [comment] 2015-09-27 17:50
Thanks for the tips @martijn00 !

Before adding this i wanted to improve the register + callback system of `MvxCachedFragmentActivity` so it can be used in someway with this ( #86 ). I'll PR this changes ASAP this week.

**Comment by martijn00** [comment] 2015-09-27 18:15
Thanks! Your PR's looks nice, i'll give it some testing sometime soon. You might want to take a look at https://github.com/MvvmCross/MvvmCross-AndroidSupport/pull/63 to see how that affects your PR.

**Comment by thefex** [comment] 2015-12-20 19:06
Take a look at my commit:
https://github.com/thefex/MvvmCross-AndroidSupport/commit/b257e33b540b76cdd9783aa743a9ff4a4881cad4

That finally fixes problem mentioned in issue.
The problem is that Presenter Show (for Activity) acts like asynchronous method. IMvxAndroidCurrentTopActivity does not return immediately new Activity after .Show call.

**Comment by martijn00** [comment] 2015-12-23 11:21
Fixed in: https://github.com/MvvmCross/MvvmCross-AndroidSupport/pull/149

**Closed as completed by martijn00** 2015-12-23 11:21 UTC

**Comment by ahadk** [comment] 2016-08-31 10:52
FragmentOne.cs
`using Android.OS;
using Android.Runtime;
using Android.Views;
using SchoolApp.Core.ViewModels;
using MvvmCross.Droid.Shared.Attributes;
using MvvmCross.Droid.Support.V4;

namespace SchoolApp.Droid
{

```
[MvxFragmentAttribute(typeof(MainViewModel), Resource.Id.frameLayout)]
[Register("schoolapp.droid.FragmentOne")]
public class FragmentOne : MvxFragment<FragmentOneViewModel>
{
    public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
    {
        return inflater.Inflate(Resource.Layout.MyListView, container, false);
    }
}
```

}`

FragmentOneViewModel.cs
`using MvvmCross.Core.ViewModels;

namespace SchoolApp.Core.ViewModels
{
    public class FragmentOneViewModel : MvxViewModel
    {
    }
}`

MainActivity.cs
`using System.Linq;
using Android.App;
using Android.OS;
using Android.Support.V4.Widget;
using Android.Support.V7.App;
using Android.Views;
using Android.Widget;
using SchoolApp.Core.ViewModels;
using MvvmCross.Droid.Support.V7.AppCompat;
using Fragment = Android.Support.V4.App.Fragment;
using Toolbar = Android.Support.V7.Widget.Toolbar;

namespace SchoolApp.Droid
{

```
[Activity(Label = "@string/app_name", MainLauncher = true)]
public class MainActivity : MvxCachingFragmentCompatActivity<MainViewModel>
{
    ActionBarDrawerToggle _drawerToggle;

    ListView _drawerListView;

    DrawerLayout _drawerLayout;

    Fragment[] _fragments = { new FragmentOne(), new FragmentTwo() };
    protected override void OnCreate(Bundle bundle)
    {
        base.OnCreate(bundle);

        SetContentView(Resource.Layout.DrawerScreen);

        var toolbar = FindViewById<Toolbar>(Resource.Id.toolbar);
        SetSupportActionBar(toolbar);

        SupportActionBar.SetDisplayHomeAsUpEnabled(true);

        _drawerListView = FindViewById<ListView>(Resource.Id.drawerListView);
        _drawerListView.ItemClick += (s, e) => ShowFragmentAt(e.Position);
        _drawerListView.Adapter = new ArrayAdapter<string>(this, global::Android.Resource.Layout.SimpleListItem1, ViewModel.MenuItems.ToArray());

        _drawerLayout = FindViewById<DrawerLayout>(Resource.Id.drawerLayout);

        _drawerToggle = new ActionBarDrawerToggle(this, _drawerLayout, Resource.String.OpenDrawerString, Resource.String.CloseDrawerString);

        _drawerLayout.SetDrawerListener(_drawerToggle);

        ShowFragmentAt(0);
    }

    void ShowFragmentAt(int position)
    {
        //SupportFragmentManager
        //.BeginTransaction()
        //.Replace(Resource.Id.frameLayout, _fragments[position])
        //.Commit();

        ViewModel.NavigateTo(position);

        Title = ViewModel.MenuItems.ElementAt(position);

        _drawerLayout.CloseDrawer(_drawerListView);
    }

    protected override void OnPostCreate(Bundle savedInstanceState)
    {
        _drawerToggle.SyncState();

        base.OnPostCreate(savedInstanceState);
    }

    public override bool OnOptionsItemSelected(IMenuItem item)
    {
        if (_drawerToggle.OnOptionsItemSelected(item))
            return true;

        return base.OnOptionsItemSelected(item);
    }
}
```

}
`
MainViewModel.cs
`using MvvmCross.Core.ViewModels;
using System;
using System.Collections.Generic;

namespace SchoolApp.Core.ViewModels
{
    public class MainViewModel : MvxViewModel
    {
        readonly Type[] _menuItemTypes1 = {
            typeof(FragmentOneViewModel),
            typeof(FragmentTwoViewModel),
        };

```
    public IEnumerable<string> MenuItems { get; private set; } = new[] { "My List", "My Settings" };

    public void ShowDefaultMenuItem()
    {
        NavigateTo(0);
    }

    public void NavigateTo(int position)
    {
            ShowViewModel(_menuItemTypes1[position]);
    }
}

public class DrawerItem : Tuple<string, Type>
{
    public DrawerItem(string displayName, Type viewModelType)
        : base(displayName, viewModelType)
    { }

    public string DisplayName
    {
        get { return Item1; }
    }

    public Type ViewModelType
    {
        get { return Item2; }
    }
}
```

}`

plugin used : 
mvvmCross.Droid.shared (not using droid.fragging)
Droid.support.V4
droid.support.v7.AppCompat

 Having Error: 
Unable to find explicit activity class {com.grappetite.schoolapp/schoolapp.droid.FragmentOne}; have you declared this activity in your AndroidManifest.xml?

Things i done :
removing / adding plugins 
try checking manifest.xml  (not useful to edit since it will override on runtime)

Possible guess :
somethings seems wrong with register annotation, can anyone point out what going wrong? Thanks  :)

**Comment by Cheesebaron** [comment] 2016-08-31 10:59
Could you please create a new issue instead of writing in this old closed one?

**Comment by ahadk** [comment] 2016-08-31 11:07
done.
https://github.com/MvvmCross/MvvmCross-AndroidSupport/issues/287
