### ISSUE TITLE
Android example solution is throwing error at runtime.

### ISSUE THREAD

**Issue by glalwani2** [MvvmCross/MvvmCross-AndroidSupport#242] opened 2016-05-21 11:03 UTC
Hi,
Today I cloned the solution to my Visual Studio 2015 Professional, when I tried to build and run the solution, then the solution built successfully, but threw the below exception at runtime when I tried to view any example fom drawer layout.

Java.Lang.ClassNotFoundException: Didn't find class "android.view.MvxRecyclerView" on path: DexPathList[[zip file "/data/app/com.mvvmcross.androidsupport.example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mvvmcross.androidsupport.example-1/lib/x86, /data/app/com.mvvmcross.androidsupport.example-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]

Please let me know If I missed anything during the setup for running the sample solution.

Thank you all.

**Comment by kjeremy** [comment] 2016-05-25 13:46
Looks like a duplicate of #244

**Closed as completed** 2016-05-25 14:53 UTC
